package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Brands generated by hbm2java
 */
public class Brands implements java.io.Serializable {

	private String brandName;
	private Integer brandId;
	private String subCategories;

	public Brands() {
	}

	public Brands(String brandName) {
		this.brandName = brandName;
	}

	public Brands(String brandName, Integer brandId, String subCategories) {
		this.brandName = brandName;
		this.brandId = brandId;
		this.subCategories = subCategories;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	public String getSubCategories() {
		return this.subCategories;
	}

	public void setSubCategories(String subCategories) {
		this.subCategories = subCategories;
	}

}
