package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private String catName;
	private Integer catId;

	public Categories() {
	}

	public Categories(String catName) {
		this.catName = catName;
	}

	public Categories(String catName, Integer catId) {
		this.catName = catName;
		this.catId = catId;
	}

	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

}
