package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Delievery generated by hbm2java
 */
public class Delievery implements java.io.Serializable {

	private int delieveryId;
	private String delieveryAddress;
	private String delieveryDate;

	public Delievery() {
	}

	public Delievery(int delieveryId) {
		this.delieveryId = delieveryId;
	}

	public Delievery(int delieveryId, String delieveryAddress, String delieveryDate) {
		this.delieveryId = delieveryId;
		this.delieveryAddress = delieveryAddress;
		this.delieveryDate = delieveryDate;
	}

	public int getDelieveryId() {
		return this.delieveryId;
	}

	public void setDelieveryId(int delieveryId) {
		this.delieveryId = delieveryId;
	}

	public String getDelieveryAddress() {
		return this.delieveryAddress;
	}

	public void setDelieveryAddress(String delieveryAddress) {
		this.delieveryAddress = delieveryAddress;
	}

	public String getDelieveryDate() {
		return this.delieveryDate;
	}

	public void setDelieveryDate(String delieveryDate) {
		this.delieveryDate = delieveryDate;
	}

}
