package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * OrdersDelievery generated by hbm2java
 */
public class OrdersDelievery implements java.io.Serializable {

	private OrdersDelieveryId id;

	public OrdersDelievery() {
	}

	public OrdersDelievery(OrdersDelieveryId id) {
		this.id = id;
	}

	public OrdersDelieveryId getId() {
		return this.id;
	}

	public void setId(OrdersDelieveryId id) {
		this.id = id;
	}

}
