package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * OrdersDelieveryId generated by hbm2java
 */
public class OrdersDelieveryId implements java.io.Serializable {

	private int orderId;
	private int delieveryId;

	public OrdersDelieveryId() {
	}

	public OrdersDelieveryId(int orderId, int delieveryId) {
		this.orderId = orderId;
		this.delieveryId = delieveryId;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public int getDelieveryId() {
		return this.delieveryId;
	}

	public void setDelieveryId(int delieveryId) {
		this.delieveryId = delieveryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdersDelieveryId))
			return false;
		OrdersDelieveryId castOther = (OrdersDelieveryId) other;

		return (this.getOrderId() == castOther.getOrderId()) && (this.getDelieveryId() == castOther.getDelieveryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getDelieveryId();
		return result;
	}

}
