package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Payments generated by hbm2java
 */
public class Payments implements java.io.Serializable {

	private int payId;
	private Double amount;
	private Integer orderId;
	private Integer userId;

	public Payments() {
	}

	public Payments(int payId) {
		this.payId = payId;
	}

	public Payments(int payId, Double amount, Integer orderId, Integer userId) {
		this.payId = payId;
		this.amount = amount;
		this.orderId = orderId;
		this.userId = userId;
	}

	public int getPayId() {
		return this.payId;
	}

	public void setPayId(int payId) {
		this.payId = payId;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
