package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int prodId;
	private String brandName;
	private String prodName;
	private Float prodPrice;

	public Product() {
	}

	public Product(int prodId) {
		this.prodId = prodId;
	}

	public Product(int prodId, String brandName, String prodName, Float prodPrice) {
		this.prodId = prodId;
		this.brandName = brandName;
		this.prodName = prodName;
		this.prodPrice = prodPrice;
	}

	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getProdName() {
		return this.prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	public Float getProdPrice() {
		return this.prodPrice;
	}

	public void setProdPrice(Float prodPrice) {
		this.prodPrice = prodPrice;
	}

}
