package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * ProductUsers generated by hbm2java
 */
public class ProductUsers implements java.io.Serializable {

	private ProductUsersId id;

	public ProductUsers() {
	}

	public ProductUsers(ProductUsersId id) {
		this.id = id;
	}

	public ProductUsersId getId() {
		return this.id;
	}

	public void setId(ProductUsersId id) {
		this.id = id;
	}

}
