package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Productdetails generated by hbm2java
 */
public class Productdetails implements java.io.Serializable {

	private int prDetId;
	private String brand;
	private String colour;
	private String model;
	private Float price;
	private String productName;
	private String warranty;
	private Integer productId;

	public Productdetails() {
	}

	public Productdetails(int prDetId) {
		this.prDetId = prDetId;
	}

	public Productdetails(int prDetId, String brand, String colour, String model, Float price, String productName,
			String warranty, Integer productId) {
		this.prDetId = prDetId;
		this.brand = brand;
		this.colour = colour;
		this.model = model;
		this.price = price;
		this.productName = productName;
		this.warranty = warranty;
		this.productId = productId;
	}

	public int getPrDetId() {
		return this.prDetId;
	}

	public void setPrDetId(int prDetId) {
		this.prDetId = prDetId;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getColour() {
		return this.colour;
	}

	public void setColour(String colour) {
		this.colour = colour;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getWarranty() {
		return this.warranty;
	}

	public void setWarranty(String warranty) {
		this.warranty = warranty;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

}
