package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * ProductSeller generated by hbm2java
 */
public class ProductSeller implements java.io.Serializable {

	private ProductSellerId id;

	public ProductSeller() {
	}

	public ProductSeller(ProductSellerId id) {
		this.id = id;
	}

	public ProductSellerId getId() {
		return this.id;
	}

	public void setId(ProductSellerId id) {
		this.id = id;
	}

}
