package entities;
// Generated Feb 20, 2018 6:22:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Userdetails generated by hbm2java
 */
public class Userdetails implements java.io.Serializable {

	private int userId;
	private String password;
	private String userName;

	public Userdetails() {
	}

	public Userdetails(int userId) {
		this.userId = userId;
	}

	public Userdetails(int userId, String password, String userName) {
		this.userId = userId;
		this.password = password;
		this.userName = userName;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
