package entities;
// Generated Feb 20, 2018 6:52:46 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Complain generated by hbm2java
 */
@Entity
@Table(name = "complain", catalog = "HibernateTask")
public class Complain implements java.io.Serializable {

	private int complainSno;
	private String aboutDelievery;
	private String aboutProduct;
	private String aboutSeller;
	private Integer userId;

	public Complain() {
	}

	public Complain(int complainSno) {
		this.complainSno = complainSno;
	}

	public Complain(int complainSno, String aboutDelievery, String aboutProduct, String aboutSeller, Integer userId) {
		this.complainSno = complainSno;
		this.aboutDelievery = aboutDelievery;
		this.aboutProduct = aboutProduct;
		this.aboutSeller = aboutSeller;
		this.userId = userId;
	}

	@Id

	@Column(name = "ComplainSNo", unique = true, nullable = false)
	public int getComplainSno() {
		return this.complainSno;
	}

	public void setComplainSno(int complainSno) {
		this.complainSno = complainSno;
	}

	@Column(name = "AboutDelievery")
	public String getAboutDelievery() {
		return this.aboutDelievery;
	}

	public void setAboutDelievery(String aboutDelievery) {
		this.aboutDelievery = aboutDelievery;
	}

	@Column(name = "AboutProduct")
	public String getAboutProduct() {
		return this.aboutProduct;
	}

	public void setAboutProduct(String aboutProduct) {
		this.aboutProduct = aboutProduct;
	}

	@Column(name = "AboutSeller")
	public String getAboutSeller() {
		return this.aboutSeller;
	}

	public void setAboutSeller(String aboutSeller) {
		this.aboutSeller = aboutSeller;
	}

	@Column(name = "User_ID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
