package entities;
// Generated Feb 20, 2018 6:52:46 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Delievery generated by hbm2java
 */
@Entity
@Table(name = "delievery", catalog = "HibernateTask")
public class Delievery implements java.io.Serializable {

	private int delieveryId;
	private String delieveryAddress;
	private String delieveryDate;

	public Delievery() {
	}

	public Delievery(int delieveryId) {
		this.delieveryId = delieveryId;
	}

	public Delievery(int delieveryId, String delieveryAddress, String delieveryDate) {
		this.delieveryId = delieveryId;
		this.delieveryAddress = delieveryAddress;
		this.delieveryDate = delieveryDate;
	}

	@Id

	@Column(name = "DelieveryID", unique = true, nullable = false)
	public int getDelieveryId() {
		return this.delieveryId;
	}

	public void setDelieveryId(int delieveryId) {
		this.delieveryId = delieveryId;
	}

	@Column(name = "DelieveryAddress")
	public String getDelieveryAddress() {
		return this.delieveryAddress;
	}

	public void setDelieveryAddress(String delieveryAddress) {
		this.delieveryAddress = delieveryAddress;
	}

	@Column(name = "DelieveryDate")
	public String getDelieveryDate() {
		return this.delieveryDate;
	}

	public void setDelieveryDate(String delieveryDate) {
		this.delieveryDate = delieveryDate;
	}

}
