package entities;
// Generated Feb 20, 2018 6:52:46 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrdersDelievery generated by hbm2java
 */
@Entity
@Table(name = "orders_delievery", catalog = "HibernateTask")
public class OrdersDelievery implements java.io.Serializable {

	private OrdersDelieveryId id;

	public OrdersDelievery() {
	}

	public OrdersDelievery(OrdersDelieveryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "Order_ID", nullable = false)),
			@AttributeOverride(name = "delieveryId", column = @Column(name = "Delievery_ID", nullable = false)) })
	public OrdersDelieveryId getId() {
		return this.id;
	}

	public void setId(OrdersDelieveryId id) {
		this.id = id;
	}

}
