package entities;
// Generated Feb 20, 2018 6:52:46 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name = "payments", catalog = "HibernateTask")
public class Payments implements java.io.Serializable {

	private int payId;
	private Double amount;
	private Integer orderId;
	private Integer userId;

	public Payments() {
	}

	public Payments(int payId) {
		this.payId = payId;
	}

	public Payments(int payId, Double amount, Integer orderId, Integer userId) {
		this.payId = payId;
		this.amount = amount;
		this.orderId = orderId;
		this.userId = userId;
	}

	@Id

	@Column(name = "payID", unique = true, nullable = false)
	public int getPayId() {
		return this.payId;
	}

	public void setPayId(int payId) {
		this.payId = payId;
	}

	@Column(name = "Amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "Order_ID")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "User_ID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
