package entities;
// Generated Feb 20, 2018 6:52:46 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paymentoptions generated by hbm2java
 */
@Entity
@Table(name = "paymentoptions", catalog = "HibernateTask")
public class Paymentoptions implements java.io.Serializable {

	private int payOptionsId;
	private Integer cvvno;
	private Integer payId;
	private String bank;
	private String checkNo;
	private String creaditCardNo;

	public Paymentoptions() {
	}

	public Paymentoptions(int payOptionsId) {
		this.payOptionsId = payOptionsId;
	}

	public Paymentoptions(int payOptionsId, Integer cvvno, Integer payId, String bank, String checkNo,
			String creaditCardNo) {
		this.payOptionsId = payOptionsId;
		this.cvvno = cvvno;
		this.payId = payId;
		this.bank = bank;
		this.checkNo = checkNo;
		this.creaditCardNo = creaditCardNo;
	}

	@Id

	@Column(name = "Pay_Options_ID", unique = true, nullable = false)
	public int getPayOptionsId() {
		return this.payOptionsId;
	}

	public void setPayOptionsId(int payOptionsId) {
		this.payOptionsId = payOptionsId;
	}

	@Column(name = "CVVNO")
	public Integer getCvvno() {
		return this.cvvno;
	}

	public void setCvvno(Integer cvvno) {
		this.cvvno = cvvno;
	}

	@Column(name = "Pay_ID")
	public Integer getPayId() {
		return this.payId;
	}

	public void setPayId(Integer payId) {
		this.payId = payId;
	}

	@Column(name = "Bank")
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	@Column(name = "CheckNo")
	public String getCheckNo() {
		return this.checkNo;
	}

	public void setCheckNo(String checkNo) {
		this.checkNo = checkNo;
	}

	@Column(name = "creaditCardNo")
	public String getCreaditCardNo() {
		return this.creaditCardNo;
	}

	public void setCreaditCardNo(String creaditCardNo) {
		this.creaditCardNo = creaditCardNo;
	}

}
