package entities;
// Generated Feb 20, 2018 6:52:46 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductUsers generated by hbm2java
 */
@Entity
@Table(name = "product_users", catalog = "HibernateTask")
public class ProductUsers implements java.io.Serializable {

	private ProductUsersId id;

	public ProductUsers() {
	}

	public ProductUsers(ProductUsersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "Product_ID", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "User_ID", nullable = false)) })
	public ProductUsersId getId() {
		return this.id;
	}

	public void setId(ProductUsersId id) {
		this.id = id;
	}

}
