package entities;
// Generated Feb 20, 2018 6:52:46 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductSeller generated by hbm2java
 */
@Entity
@Table(name = "product_seller", catalog = "HibernateTask")
public class ProductSeller implements java.io.Serializable {

	private ProductSellerId id;

	public ProductSeller() {
	}

	public ProductSeller(ProductSellerId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "Product_ID", nullable = false)),
			@AttributeOverride(name = "sellerId", column = @Column(name = "Seller_ID", nullable = false)) })
	public ProductSellerId getId() {
		return this.id;
	}

	public void setId(ProductSellerId id) {
		this.id = id;
	}

}
