package entities;
// Generated Feb 20, 2018 6:52:46 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Refoundorreplace generated by hbm2java
 */
@Entity
@Table(name = "refoundorreplace", catalog = "HibernateTask")
public class Refoundorreplace implements java.io.Serializable {

	private int reId;
	private Double refoundAmount;
	private String replaceProduct;
	private Integer payOptionsId;

	public Refoundorreplace() {
	}

	public Refoundorreplace(int reId) {
		this.reId = reId;
	}

	public Refoundorreplace(int reId, Double refoundAmount, String replaceProduct, Integer payOptionsId) {
		this.reId = reId;
		this.refoundAmount = refoundAmount;
		this.replaceProduct = replaceProduct;
		this.payOptionsId = payOptionsId;
	}

	@Id

	@Column(name = "reID", unique = true, nullable = false)
	public int getReId() {
		return this.reId;
	}

	public void setReId(int reId) {
		this.reId = reId;
	}

	@Column(name = "RefoundAmount", precision = 22, scale = 0)
	public Double getRefoundAmount() {
		return this.refoundAmount;
	}

	public void setRefoundAmount(Double refoundAmount) {
		this.refoundAmount = refoundAmount;
	}

	@Column(name = "ReplaceProduct")
	public String getReplaceProduct() {
		return this.replaceProduct;
	}

	public void setReplaceProduct(String replaceProduct) {
		this.replaceProduct = replaceProduct;
	}

	@Column(name = "Pay_Options_ID")
	public Integer getPayOptionsId() {
		return this.payOptionsId;
	}

	public void setPayOptionsId(Integer payOptionsId) {
		this.payOptionsId = payOptionsId;
	}

}
